name: simple_todo_app
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.2.1
  cloud_firestore: ^2.5.3
  dartz: ^0.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^0.15.0
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  google_sign_in: ^5.1.1
  implicitly_animated_reorderable_list: ^0.4.1
  intl: ^0.17.0
  json_annotation: ^4.1.0
  rxdart: ^0.27.2
  reorderables: ^0.4.1
  auto_route: ^2.4.2
  material_design_icons_flutter: ^4.0.5955
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  hive: ^2.0.4
  lottie: ^1.2.1


dev_dependencies:
  bloc_test: ^8.3.0
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  freezed: ^0.15.0+1
  json_serializable: ^5.0.2
  mocktail: ^0.1.0
  very_good_analysis: ^2.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/icon_google.svg
    - assets/animations/whiteLoading.json
    - assets/animations/loading.json