name: simple_todo_app
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^8.0.0-dev.3
  cloud_firestore: ^2.5.3
  dartz: ^0.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0-dev.2
  flutter_keyboard_visibility: ^5.0.3
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^0.15.0
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.3
  google_sign_in: ^5.1.1
  intl: ^0.17.0
  json_annotation: ^4.3.0
  rxdart: ^0.27.2
  flutter_svg: ^0.23.0+1
  google_fonts: ^2.1.0
  lottie: ^1.2.1
  path_provider: ^2.0.5
  sembast: ^3.1.1
  bottom_navy_bar: ^6.0.0
  uuid: ^3.0.5


dev_dependencies:
  bloc_test: ^9.0.0-dev.3
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter
  freezed: ^0.15.0+1
  json_serializable: ^6.0.1
  mocktail: ^0.2.0
  very_good_analysis: ^2.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/icon_google.svg
    - assets/images/icon_trello.svg
    - assets/images/icon_apple.svg
    - assets/images/logout_icon.svg
    - assets/animations/whiteLoading.json
    - assets/animations/loading.json
